title: Je1ghtxyuN
subtitle: Code, Anime, Games, and Coffee.
description: ""
keywords:
  - personal website
  - technical blog
  - portfolio
  - VR
  - HCI
  - game development
author: Je1ghtxyuN
language:
  - en
  - zh-CN
  - ja
timezone: Asia/Shanghai

url: https://je1ght.top
root: /
permalink: posts/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: []

new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: prismjs
highlight:
  enable: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

index_generator:
  per_page: 8
  order_by: -date

default_category: uncategorized
category_map:
tag_map:

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime

per_page: 8
pagination_dir: page

include:
exclude:
ignore:

theme: butterfly

search:
  path: search.json
  field: all
  content: true
  format: striptags

deploy:
  type: ''
